version: "3"
services:
  spring_app:
    build: ./docker_files/spring_app
    depends_on:
      - postgres_spring
    container_name: spring_app
    volumes:
      - ./spring_app:/spring_app
    ports:
      - 54321:54321
    restart: unless-stopped
  postgres_spring:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./postgres_spring:/var/lib/postgresql/data
    environment:
         - POSTGRES_PASSWORD=password
         - POSTGRES_USER=user
         - POSTGRES_DB=rezeptmeister
    restart: unless-stopped
    command: -p 5000
    ports:
     - 5000:5000
